version: '3'
services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - todo-data:/app/data
    environment:
      - NODE_ENV=production

volumes:
  todo-data: