# Use Node.js v14 as the base image
FROM node:14 as build

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Build the React app for production
RUN npm run build

# Use NGINX as the production server
FROM nginx:alpine

# Copy the built app to NGINX's web root directory
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Expose the port the app runs on (optional since NGINX will serve the app)
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
